version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.8.12-management-alpine"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  database:
    image: "mariadb:10.5.9"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
